module Game exposing  (..)

import Browser
import Browser.Navigation as Nav
import Browser.Dom exposing (getViewport)
import Browser.Events exposing (onAnimationFrameDelta)
import Game.Resources as Resources exposing (..)
import Game.TwoD as Game2d
import Game.TwoD.Camera as Camera exposing (..)
import Game.TwoD.Render as Render exposing (..)
import Html exposing (Html, div, img, text, pre)
import Html.Attributes exposing (style, src)
import Keyboard
import Keyboard.Arrows
import Task
import Array

-- MODEL


type alias Model =
  { navKey : Nav.Key
  , player : Player
  , sword : Sword
  , enemy : Player
  , resources : Resources
  , keys : List Keyboard.Key
  , time : Float
  , screen : ( Int, Int )
  , camera : Camera
  }


type Msg
  = Tick Float
  | Resources Resources.Msg
  | Keys Keyboard.Msg


type alias Player =
  { x : Float
  , y : Float
  , vx : Float
  , vy : Float
  , dir : Direction
  }

type alias Sword =
  { x : Float
  , y : Float
  , dir : Direction
  , action : Action
  }

type Direction
  = Left
  | Right
  | Up
  | Down
  | Idle

type Action
  = NotAttack
  | Attack

type alias Input =
  { x : Int, y : Int }

-- https://stackoverflow.com/questions/52350505/accessing-elements-in-2-dimensional-array-elm
level2Tilemap : Array.Array ( Array.Array Char )
level2Tilemap =
  Array.fromList
    [ Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTEETTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFFFFFFFXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFTTTTTTFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFTTTTTTFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTFFFFFFFFFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTFFFFFFFFFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXFFFFFFFFFFFFFTTTTTTFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXFFFFFFFFFFFFFTTTTTTFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTTTTTTFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFFFFFFFFFFFFFFTTTTTTFFFFFFFFFFFXXXXXXXXXXXXXXXXFFFFFFFFXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFTTTTTTFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    , Array.fromList (String.toList "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
  ]

getTileTypeFromTileMap : Array.Array ( Array.Array Char ) -> Float -> Float -> Maybe Char
getTileTypeFromTileMap array x y =
    {-
    let
        _ = Debug.log "[getTileTypeFromTileMap] x" (floor x)
        _ = Debug.log "[getTileTypeFromTileMap] y" (floor y)
    in-}
    Array.get (127 - (floor y)) array
    |> Maybe.andThen (Array.get (floor x))
    --|> Debug.log "[getTileTypeFromTileMap] tile"

getNavKey : Model -> Nav.Key
getNavKey model =
  model.navKey


initPlayer : Player
initPlayer =
  { x = 56
  , y = 10
  , vx = 0
  , vy = 0
  , dir = Idle
  }

initSword : Player -> Sword
initSword player =
  { x = player.x + 0.75
  , y = player.y + 0.5
  , dir = Idle
  , action = NotAttack
  }

initEnemy : Player
initEnemy =
  { x = 57
  , y = 9
  , vx = 0
  , vy = 3
  , dir = Up
  }

init : Nav.Key -> ( Model, Cmd Msg )
init navKey =
  ( { navKey = navKey
    , player = initPlayer
    , sword = initSword initPlayer
    , enemy = initEnemy
    , resources = Resources.init
    , keys = []
    , time = 0
    , screen = ( 1024, 512 )
    , camera = Camera.fixedArea (32 * 16) ( 0, 0 )
    }
  , Cmd.map Resources (Resources.loadTextures texturesList )
  )


texturesList : List String
texturesList =
  [ "assets/player/playerIdle.png"
  , "assets/player/playerRight.png"
  , "assets/player/playerLeft.png"
  , "assets/player/playerUp.png"
  , "assets/player/playerDown.png"
  , "assets/level/level_2.png"
  , "assets/enemy/enemyIdle.png"
  , "assets/enemy/enemyRight.png"
  , "assets/enemy/enemyLeft.png"
  , "assets/enemy/enemyUp.png"
  , "assets/enemy/enemyDown.png"
  , "assets/sword_stone.png"
  , "assets/sword_stone_attack.png"
  ]


-- UPDATE


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
  case msg of
    Tick dt ->
      ( { model
          | player = tick dt model.keys model.player
          , sword = swordPhysics dt model.player model.sword
          , enemy = enemyMovement model.enemy |> physics dt
          , time = dt + model.time
          , camera = Camera.moveTo ( model.player.x, model.player.y) model.camera
        }
        , Cmd.none
      )

    Resources rMsg ->
      ( { model | resources = Resources.update rMsg model.resources }
      , Cmd.none
      )

    Keys keyMsg ->
      let
        keys =
          Keyboard.update keyMsg model.keys
        _ = Debug.log "[model.keys]" keys
      in
        ( { model | keys = keys }, Cmd.none )


tick : Float -> List Keyboard.Key -> Player -> Player
tick dt keys player =
  let
    moveInput =
      Keyboard.Arrows.wasd keys
      --Keyboard.Arrows.arrows keys
  in
  player
    |> walk moveInput
    |> physics dt


enemyMovement : Player -> Player
enemyMovement player =
    if (toFloat (floor player.y)) == (9.0 + 5.0) then
      { player
        | dir = Down
        , vy = -3 -- -1 * player.vy
      }
    else if (toFloat (floor player.y)) == 9.0 then
      { player
        | dir = Up
        , vy = 3 -- -1 * player.vy
      }
    else player

swordPhysics : Float -> Player -> Sword -> Sword
swordPhysics dt player sword =
  { sword
  | x = player.x + 0.75
  , y = player.y + 0.5
  }

physics : Float -> Player -> Player
physics dt player =
  let
    newX = player.x + dt * player.vx
    newY = player.y + dt * player.vy
    tileType =
      if player.dir == Left then
        getTileTypeFromTileMap level2Tilemap (newX - 1) newY
      else if player.dir == Up then
        getTileTypeFromTileMap level2Tilemap newX (newY + 1)
      else
        getTileTypeFromTileMap level2Tilemap newX newY

    --_ = Debug.log "[physics] newX" newX
    --_ = Debug.log "[physics] newY" newY
  in
  { player
    | x =
        case tileType of
          Just tile ->
            if tile == 'T' then
              newX
            else player.x --(toFloat (floor player.x) - 0.1)
          Nothing ->
            player.x
    , y =
      case tileType of
        Just tile ->
          if tile == 'T' then
            newY
          else player.y --(toFloat (floor player.x) - 0.1)
        Nothing ->
          player.y
  }


walk : Input -> Player -> Player
walk keys player =
  { player
    | vx = 3 * toFloat keys.x
    , vy = 3 * toFloat keys.y
    , dir =
        if keys.x < 0 then
          Left

        else if keys.x > 0 then
          Right

        else if keys.y < 0 then
          Down

        else if keys.y > 0 then
          Up

        else
          Idle --guy.dir
  }


-- VIEW


render : Model -> List Renderable
render ({ resources, camera } as model) =
  List.concat
    [ renderBackground resources
    , [ renderPlayer resources model.player
      , renderSword resources model.sword model.keys
      , renderEnemy resources model.enemy
      ]
    ]


renderBackground : Resources -> List Renderable
renderBackground resources =
  [ Render.spriteZ
    { texture = Resources.getTexture "assets/level/level_2.png" resources
    , position = ( 0, 0, -0.9 )
    , size = ( 128, 128 )
    }
  ]

renderSword : Resources -> Sword -> List Keyboard.Key -> Renderable
renderSword resources { x, y } keys =
  Render.spriteWithOptions
    { texture =
        if List.member Keyboard.Spacebar keys then
          Resources.getTexture "assets/sword_stone_attack.png" resources
        else
          Resources.getTexture "assets/sword_stone.png" resources
    , position = ( x, y, 0.1 )
    , size =
      if List.member Keyboard.Spacebar keys then
        ( 1, 0.5 )
      else
        ( 0.5, 1 )
    , tiling = ( 1, 1 )
    , rotation = 0 -- -1
    , pivot = ( 0, 0)
    }


renderEnemy : Resources -> Player -> Renderable
renderEnemy resources { x, y, dir } =
  Render.animatedSpriteWithOptions
    { position = ( x, y, -0.1 )
    , size = ( 1, 2 )
    , texture =
        case dir of
          Left ->
            Resources.getTexture "assets/enemy/enemyLeft.png" resources

          Right ->
            Resources.getTexture "assets/enemy/enemyRight.png" resources

          Up ->
            Resources.getTexture "assets/enemy/enemyUp.png" resources

          Down ->
            Resources.getTexture "assets/enemy/enemyDown.png" resources

          Idle ->
            Resources.getTexture "assets/enemy/enemyIdle.png" resources
    , bottomLeft = ( 0, 0 )
    , topRight = ( 1, 1 )
    , duration = 1
    , numberOfFrames = 2
    , rotation = 0
    , pivot = ( 0, 0 )
    }

renderPlayer : Resources -> Player -> Renderable
renderPlayer resources { x, y, dir } =
  Render.animatedSpriteWithOptions
    { position = ( x, y, 0 )
    , size = ( 1, 2 )
    , texture =
        case dir of
          Left ->
            Resources.getTexture "assets/player/playerLeft.png" resources

          Right ->
            Resources.getTexture "assets/player/playerRight.png" resources

          Up ->
            Resources.getTexture "assets/player/playerUp.png" resources

          Down ->
            Resources.getTexture "assets/player/playerDown.png" resources

          Idle ->
            Resources.getTexture "assets/player/playerIdle.png" resources
    , bottomLeft = ( 0, 0 )
    , topRight = ( 1, 1 )
    , duration = 1
    , numberOfFrames = 2
    , rotation = 0
    , pivot = ( 0, 0 )
    }

viewPlayerCoordinates : Model -> Html Msg
viewPlayerCoordinates model =
  pre [ style "position" "absolute"
      , style "left" "448px"
      , style "top" "750px"
      ]
      [ text "Player"
      , text ("\nx: " ++ String.fromFloat model.player.x)
      , text ("\ny: " ++ String.fromFloat model.player.y)
      , text ("\nvx: " ++ String.fromFloat model.player.vx)
      , text ("\nvy: " ++ String.fromFloat model.player.vy)
      ]

view : Model -> { title : String, content : Html Msg }
view ({ time, screen } as model) =
  { title = "Game"
  , content =
    div []
      [ img [ src "assets/default_background_1920_969.png"
            , style "display" "block"
            , style "position" "relative"
            , style "left" "0px"
            , style "top" "0px"
            ] []
      , Game2d.renderWithOptions
          [ style "position" "absolute"
          , style "left" "448px"
          , style "top" "228px"
          , style "border" "solid 1px #FFF"
          ]
            { camera = model.camera
            , time = time
            , size = screen
            }
              (render model)
      , viewPlayerCoordinates model
      ]
  }

subscriptions : Model -> Sub Msg
subscriptions model =
  Sub.batch
    [ Sub.map Keys Keyboard.subscriptions
    , onAnimationFrameDelta ((\dt -> dt / 1000) >> Tick)
    ]
